- name: Docker configure in EC2 Machine
  hosts: all
  become: true
  tasks:
    - name: Updating the new EC2 Machine
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Run Docker container
      docker_container:
        name: insure-me-container
        image: rnavindevops/insureme-project:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8085:8081"
