- name: Docker configure in EC2 Machine
  hosts: all
  become: true
  tasks:
    - name: Updating the new EC2 Machine
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

        
    - name: Deploy the image and run as container
      command: docker run -itd -p 8085:8082 rnavindevops/insure-me:1.0
