- name: Docker Configure in EC2 Machine
  hosts: all
  become: true
  connection: ssh
  tasks: 
    - name: Update the New EC2 Machine
      yum:
        name: "*"
        state: latest

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: Install Docker
      yum:
        name: docker
        state: present
      when: docker_version.rc != 0
      become: true

   - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true
      
   - name: Deploy the Image and Run as Container
    command: docker run -itd -p 8084:8081 rnavindevops/insureme-app:1.0
    

